version: '3.1'

networks:
  backend:
    driver:
      bridge

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgre
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      - DEBUG=true
      - PG_TRUST_LOCALNET=true
      - DB_EXTENSION=uuid-ossp
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=gostack_desafio06,gostack_desafio06_tests
    volumes:
      - ./src/database:/var/lib/postgresql
  
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.node
    container_name: node
    ports:
      - 3333:3333
    networks:
      - backend
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
